### ISSUE TITLE
Weird configuration dump

### ISSUE THREAD

**Issue by szafranski** [szafranski/RH-ota#101]
![image](https://user-images.githubusercontent.com/23621888/77864230-bd185180-7227-11ea-9323-5940c53aefed.png)
pi 4 is doubled
server version and RH_version is "doubled"

idk what is going on

**Comment by szafranski** [comment]
gpio_reset - just added is also doubled

**Comment by DavidJJ** [comment]
This is caused by us using the "config" variable to hold both the json value, and the "flag" value. 
I think we should just get rid of the duplicated "flag" values and just use the value in the original field

eg:  if pi_4_cfg:   
     blah blah

instead of  
if pi_4_cfg:
   pi_4_FLAG = True
...

if pi_4_FLAG:
   blah blah

**Comment by szafranski** [comment]
No problem for me.

**Comment by szafranski** [comment]
Will you change this?

**Comment by szafranski** [comment]
And I think that we can abandon update_without_pdf. 

It requires us to have like whole another branch to same 2MB

**Comment by szafranski** [comment]
No clue why there is "user" with default "racer" since it was changed to "pfabi" in debug mode and pi on raspberry pi. Tried on both: pi and Linux.

![image](https://user-images.githubusercontent.com/23621888/78324018-c0874200-7573-11ea-95cc-cbba387c89f0.png)

**Comment by szafranski** [comment]
Now it shows correctly. Any clues?

**Comment by szafranski** [comment]
Has to be investigated - causing bugs

**Comment by szafranski** [comment]
Reload config in a program loop?

**Comment by DavidJJ** [comment]
I think we have this under control now.
