### ISSUE TITLE
Aliases read behavior - bad in test

### ISSUE THREAD

**Issue by szafranski** [szafranski/RH-ota#102]
after using this code to check the behavior of the aliases_read:

![image](https://user-images.githubusercontent.com/23621888/77864429-be964980-7228-11ea-8af0-3eefa50ad8f4.png)

i got this:

![image](https://user-images.githubusercontent.com/23621888/77864438-cce46580-7228-11ea-8c11-be95d7305e47.png)

**Comment by szafranski** [comment]
still shows as a list - what is why I was tryig to use temp file - it was stored correctly in file

**Comment by DavidJJ** [comment]
print("".join(read_aliases_file())

**Comment by szafranski** [comment]
thanks, figured it out ;)
