### ISSUE TITLE
I2C and boot/config not set during fresh install

### ISSUE THREAD

**Issue by sl33pydog** [szafranski/RH-ota#118]
Running beta OTA and did this on "P" version OTA. 
Running raspberry pi 3b+ .  Set config to stable.  When I do a fresh install on buster or buster lite I have to enable i2c and spi in raspi-config.  Also I have to edit boot/config.txt with:

dtparam=i2c_baudrate=75000
core_freq=250

**Comment by szafranski** [comment]
So U used main_stable or master branch?

**Comment by sl33pydog** [comment]
Main_stable

**Comment by szafranski** [comment]
oh. thanks than, we will push new ota in few days. I will ask U to check it than if U want. Thanks!

**Comment by szafranski** [comment]
Has to be fixed in "master" as well. Bug.

**Comment by szafranski** [comment]
#121 related

**Comment by szafranski** [comment]
is working now - should be tested

**Comment by szafranski** [comment]
@sl33pydog - should be working now with master release

**Comment by szafranski** [comment]
looks like it works on desktop and does not on lite. 
We should re-think system configuring part

**Comment by szafranski** [comment]
Big chance that new configuration script in master will resolve this. Will be implemented today/tomorrow

**Comment by szafranski** [comment]
It is now implemented in master branch. Yo I will know for sure if that interface was implemented or not for sure.

**Comment by szafranski** [comment]
An also in stable now

**Comment by szafranski** [comment]
Assume resolved
