### ISSUE TITLE
Nodes flashed with blink.hex instead of custom_node.hex 

### ISSUE THREAD

**Issue by kestux75** [szafranski/RH-ota#133]
I have put custom_node.hex in custom_firmware folder, but my node was flashed with blink.hex. 
I renamed my hex file to node_0.hex and put it to master folder. What did the trick for first 6 nodes, but the 7th node was flashed with blink.hex. I had to rename my hex file to blink.hex to flash my last node

**Comment by szafranski** [comment]
Hmmmm... probably some code bug. I will check out what’s is going on.


W dniu niedz., 19.04.2020 o 11:45 kestux75 <notifications@github.com>
napisał(a):

**Comment by szafranski** [comment]
I fixed it. Thanks! Should be good now. You may check.

**Comment by szafranski** [comment]
Actually - now :)
