### ISSUE TITLE
OTA still has to be reopened so wizard changes could be loaded

### ISSUE THREAD

**Issue by szafranski** [szafranski/RH-ota#138]
as in description

**Comment by DavidJJ** [comment]
What are the recreate steps?   what are you changing that is not being applied immediately?

**Comment by szafranski** [comment]
When you for example have chosen stable version of RH and save, exited and
than reopened again - so stable version is surely applied and than open a
wizard, change version to master and than open RototHazard Manager in same
“session” it still says “stable”. Same applies for beta tester mode and
updating ota etc.

W dniu czw., 23.04.2020 o 20:21 DavidJJ <notifications@github.com>
napisał(a):

**Comment by szafranski** [comment]
Sorry, issue still present.

**Comment by szafranski** [comment]
Thank. Closing now
