### ISSUE TITLE
OTA doesn't show no-config file prompt and opens "twice" and blink

### ISSUE THREAD

**Issue by szafranski** [szafranski/RH-ota#81]
To be checked

**Comment by szafranski** [comment]
Now it still blinks and no configuration prompt is showed "in the background" before blink and before software is opened at the begining.

**Comment by just-david** [comment]
steps to recreate?

**Comment by szafranski** [comment]
Remove updater-config.json and open the software.

Blinking - everytime soft is being opened and after going pack to main menu
page.

W dniu śr., 25.03.2020 o 13:48 just-david <notifications@github.com>
napisał(a):

**Comment by szafranski** [comment]
thanks David
