### ISSUE TITLE
Implement David's smart-hot-spot

### ISSUE THREAD

**Issue by szafranski** [szafranski/RH-ota#90]
Almost ready

**Comment by szafranski** [comment]
Country selection maybe loaded from json

**Comment by szafranski** [comment]
Is it tested and ready?

**Comment by DavidJJ** [comment]
I've tested it on mine.  the process is repeatable and seems to be working.

**Comment by szafranski** [comment]
Can you explain how it works (including WiFi, Ethernet and all possible usecases)? We could add that “post” to the feature description of the OTA

**Comment by szafranski** [comment]
#82 related

**Comment by szafranski** [comment]
@DavidJJ is it 100% ready? close an issue if yes :)

**Comment by szafranski** [comment]
Please :)

**Comment by DavidJJ** [comment]
Auto - hotspot has gone through testing multiple times.  Documentation could probably be improved but functionality works.
